<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SpaRoot>..\ademideinfowebsite.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:64934</SpaProxyServerUrl>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.4.19" />
		<PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="10.*-*" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdemideInfoWebsite.Application\AdemideInfoWebsite.Application.csproj" />
    <ProjectReference Include="..\ademideinfowebsite.client\ademideinfowebsite.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="..\AdemideInfoWebsite.Infrastructure\AdemideInfoWebsite.Infrastructure.csproj" />
    <ProjectReference Include="..\AdemideInfoWebsite.SharedKernel\AdemideInfoWebsite.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Extensions\" />
    <Folder Include="Filters\" />
  </ItemGroup>

</Project>
